language: python
dist: xenial
python:
- "3.6"
- "3.7"
install: pip install tox-travis codecov
script: tox
after_success: codecov

jobs:
  include:
  - python: "3.7"
    env: TOXENV=docs
  - stage: deploy
    if: tag IS present
    python: "3.7"
    install: skip
    script: skip
    after_success: skip
    deploy:
      provider: pypi
      user: codingjoe
      distributions: sdist bdist_wheel
      on:
        tags: true
      password:
            secure: "tRKeQ8GmdQVjPbyzSFQbSUuLCwpsgGAlsXjBGGFBft8A9lmGjiOPpsLjvepgwVFZ8PK5hInx4mtjQ95FGmoSyUTEdmBb+Y9uxzCYqTG6z1D8isvctsiVR6okr1/mRxnYIt8/UnClEDNAwKcry4CqDURZakKt0m86oF+gzx2EP2J77KCkv1JZF+whW9AqXMp4NVMMmve134vUi/tmWzeZyiDYLn8nJ8rFCYZCjRYwOqTxyfv37SGrxwFjWUE68cx9i58oyuuTwC16j+YqbZiG0XdFOBSSMkw1nAUMXLfJkgofZeQGkXK8W1btEIA5n/xf4Yuy/AKWTNjiT1/5lCwvwTeicXV2Bm9j62VSGtfrZF9MOcuU8Pt9wML29qm6xB3A3GnhS1cbPu7kVB9NdhwdmMypqhoAHIdB/kLFXKoSSFHl3KZQH373oq26+PNO0GEfzvDPRVHUm5hIQ0CIK9fbSu9ULQwoIib4Q2ldtnPbFW5oNhLTyFZzR7l8i/W0fzoVlSRsDWIe9sXZRRIXUDv86o8RUG8edlMUWO1Rwo8RQtezBsgqj9ggGRvE5Wy34U86meO2afA6z99MQP5fQVXZ0Anz2SRJq9bLvgMI8ysCkBw7AqsCi9ric027u2QtJ7VZ3bSsLCFCbqPO8vO0yEZvFB9Rb5zJL41+5j7tBpZ7Aj4="
